import { AptitudeQuestion } from "@/models/aptitude";

const APTITUDE_REAL_QUESTIONS: AptitudeQuestion[] = [
  {
    id: "apt-q-101",
    lesson_id: "default",
    question: "A train 125 meters long passes a man, running at 5 km/hr in the same direction in which the train is going, in 10 seconds. The speed of the train is:",
    options: ["45 km/hr", "50 km/hr", "54 km/hr", "55 km/hr"],
    correct_index: 1,
    explanation: "Speed of the train relative to man = (125/10) m/sec = 12.5 m/sec = 12.5 * (18/5) km/hr = 45 km/hr. Let speed of the train be x km/hr. Then relative speed = (x - 5) km/hr. Therefore x - 5 = 45 => x = 50 km/hr.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Wipro"],
  },
  {
    id: "apt-q-102",
    lesson_id: "default",
    question: "A can do a work in 15 days and B in 20 days. If they work on it together for 4 days, then the fraction of the work that is left is:",
    options: ["1/4", "1/10", "7/15", "8/15"],
    correct_index: 3,
    explanation: "A's 1 day's work = 1/15, B's 1 day's work = 1/20. (A + B)'s 1 day's work = (1/15 + 1/20) = 7/60. (A + B)'s 4 days' work = (7/60 * 4) = 7/15. Remaining work = 1 - 7/15 = 8/15.",
    difficulty: "easy",
    status: "published",
    companies: ["Accenture", "TCS NQT", "Cognizant"],
  },
  {
    id: "apt-q-103",
    lesson_id: "default",
    question: "If the selling price of 10 articles is equal to the cost price of 11 articles, then the gain percentage is:",
    options: ["10%", "11%", "15%", "25%"],
    correct_index: 0,
    explanation: "Let CP of 1 article be Re. 1. Then CP of 10 articles = Rs. 10. SP of 10 articles = CP of 11 articles = Rs. 11. Gain = 11 - 10 = Re. 1. Gain% = (1/10 * 100)% = 10%.",
    difficulty: "easy",
    status: "published",
    companies: ["Infosys", "Wipro", "Capgemini"],
  },
  {
    id: "apt-q-104",
    lesson_id: "default",
    question: "In how many different ways can the letters of the word 'CORPORATION' be arranged so that the vowels always come together?",
    options: ["810", "1440", "2880", "50400"],
    correct_index: 3,
    explanation: "In 'CORPORATION', we treat the vowels O, O, A, I, O as one letter. Thus we have C, R, P, R, T, N and (OOAIO). 7 letters of which R occurs 2 times = 7!/2! = 2520 ways. Now 5 vowels where O occurs 3 times = 5!/3! = 20 ways. Total arrangements = 2520 * 20 = 50400.",
    difficulty: "hard",
    status: "published",
    companies: ["TCS NQT", "Goldman Sachs", "Amazon"],
  },
  {
    id: "apt-q-105",
    lesson_id: "default",
    question: "The sum of the ages of 5 children born at the intervals of 3 years each is 50 years. What is the age of the youngest child?",
    options: ["4 years", "8 years", "10 years", "None of these"],
    correct_index: 0,
    explanation: "Let the ages of children be x, (x + 3), (x + 6), (x + 9), (x + 12) years. Then x + (x+3) + (x+6) + (x+9) + (x+12) = 50 => 5x + 30 = 50 => x = 4 years.",
    difficulty: "medium",
    status: "published",
    companies: ["Wipro", "HCL", "TCS NQT"],
  },
  {
    id: "apt-q-106",
    lesson_id: "default",
    question: "A vendor bought toffees at 6 for a rupee. How many for a rupee must he sell to gain 20%?",
    options: ["3", "4", "5", "6"],
    correct_index: 2,
    explanation: "CP of 6 toffees = Re. 1. SP of 6 toffees to gain 20% = 120% of 1 = Rs. 1.20. For Rs. 1.20, toffees sold = 6. For Re. 1, toffees sold = 6 / 1.20 = 5.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Deloitte"],
  },
  {
    id: "apt-q-107",
    lesson_id: "default",
    question: "Two pipes A and B can fill a tank in 20 and 30 minutes respectively. If both pipes are used together, then how long will it take to fill the tank?",
    options: ["10 mins", "12 mins", "15 mins", "25 mins"],
    correct_index: 1,
    explanation: "Part filled by A in 1 min = 1/20. Part filled by B in 1 min = 1/30. (A + B)'s 1 minute work = 1/20 + 1/30 = 5/60 = 1/12. Hence, both pipes can fill the tank in 12 minutes.",
    difficulty: "easy",
    status: "published",
    companies: ["Accenture", "Cognizant", "TCS NQT"],
  },
  {
    id: "apt-q-108",
    lesson_id: "default",
    question: "A boat can travel with a speed of 13 km/hr in still water. If the speed of the stream is 4 km/hr, find the time taken by the boat to go 68 km downstream.",
    options: ["2 hours", "3 hours", "4 hours", "5 hours"],
    correct_index: 2,
    explanation: "Speed downstream = (13 + 4) km/hr = 17 km/hr. Time taken to travel 68 km downstream = 68 / 17 = 4 hours.",
    difficulty: "easy",
    status: "published",
    companies: ["Amazon", "TCS NQT", "Wipro"],
  },
  {
    id: "apt-q-109",
    lesson_id: "default",
    question: "The average of 20 numbers is zero. Of them, at the most, how many may be greater than zero?",
    options: ["0", "1", "10", "19"],
    correct_index: 3,
    explanation: "Average of 20 numbers = 0 => Sum of 20 numbers = 0. It is possible that 19 numbers are positive and the 20th number is negative equal to the sum of the 19 positive numbers. Thus, at most 19 can be greater than zero.",
    difficulty: "medium",
    status: "published",
    companies: ["Google", "Infosys", "TCS NQT"],
  },
  {
    id: "apt-q-110",
    lesson_id: "default",
    question: "At what rate of simple interest per annum will a sum of money double itself in 8 years?",
    options: ["10%", "12.5%", "15%", "20%"],
    correct_index: 1,
    explanation: "Let principal = P. Then Amount = 2P => Simple Interest = 2P - P = P. Rate = (100 * SI) / (P * T) = (100 * P) / (P * 8) = 12.5% per annum.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "HCL", "Capgemini"],
  },
  {
    id: "apt-q-111",
    lesson_id: "default",
    question: "A sum of money at compound interest amounts to thrice itself in 3 years. In how many years will it be 9 times itself?",
    options: ["6 years", "9 years", "12 years", "15 years"],
    correct_index: 0,
    explanation: "Amount = P(1 + r/100)^n. Given 3P = P(1 + r/100)^3 => (1 + r/100)^3 = 3. To get 9 times: 9P = P(1 + r/100)^t => 9 = 3^2 = ((1 + r/100)^3)^2 = (1 + r/100)^6. Therefore, t = 6 years.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Wipro", "Goldman Sachs"],
  },
  {
    id: "apt-q-112",
    lesson_id: "default",
    question: "In a mixture of 60 litres, the ratio of milk and water is 2 : 1. If this ratio is to be 1 : 2, then the quantity of water to be further added is:",
    options: ["20 litres", "30 litres", "40 litres", "60 litres"],
    correct_index: 3,
    explanation: "Quantity of milk = (60 * 2/3) = 40 litres, water in mixture = 20 litres. Let x litres of water be added. Then 40 / (20 + x) = 1 / 2 => 20 + x = 80 => x = 60 litres.",
    difficulty: "medium",
    status: "published",
    companies: ["Amazon", "TCS NQT", "Infosys"],
  },
  {
    id: "apt-q-113",
    lesson_id: "default",
    question: "A bag contains 6 white and 4 black balls. Two balls are drawn at random. Find the probability that they are of the same colour.",
    options: ["1/2", "7/15", "8/15", "1/9"],
    correct_index: 1,
    explanation: "Total balls = 10. Number of ways of drawing 2 balls = 10C2 = 45. Ways of drawing 2 white = 6C2 = 15. Ways of drawing 2 black = 4C2 = 6. Favorable ways = 15 + 6 = 21. Probability = 21/45 = 7/15.",
    difficulty: "hard",
    status: "published",
    companies: ["Google", "TCS NQT", "Accenture"],
  },
  {
    id: "apt-q-114",
    lesson_id: "default",
    question: "A rectangle's length is increased by 20% and its width is decreased by 20%. What is the percentage change in its area?",
    options: ["No change", "4% increase", "4% decrease", "2% decrease"],
    correct_index: 2,
    explanation: "Net percentage change = (+20) + (-20) + (+20 * -20) / 100 = 0 - 4 = -4%. Hence, there is a 4% decrease in area.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Cognizant", "Wipro"],
  },
  {
    id: "apt-q-115",
    lesson_id: "default",
    question: "What is the unit digit in the product (2467)^153 * (341)^72?",
    options: ["1", "3", "7", "9"],
    correct_index: 2,
    explanation: "Unit digit in (341)^72 is 1. Unit digit in (2467)^153 is same as unit digit in 7^153. Dividing exponent 153 by 4 leaves remainder 1. So unit digit of 7^1 = 7. Product unit digit = 7 * 1 = 7.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Deloitte"],
  },
  {
    id: "apt-q-116",
    lesson_id: "default",
    question: "Two trains of length 150 m and 250 m run on parallel tracks in opposite directions at speeds of 45 km/hr and 27 km/hr respectively. In what time will they cross each other?",
    options: ["15 seconds", "20 seconds", "25 seconds", "30 seconds"],
    correct_index: 1,
    explanation: "Relative speed = (45 + 27) = 72 km/hr = 72 * (5/18) = 20 m/sec. Total distance to be covered = 150 + 250 = 400 m. Time taken = 400 / 20 = 20 seconds.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Wipro", "Amazon"],
  },
  {
    id: "apt-q-117",
    lesson_id: "default",
    question: "A and B entered into a partnership investing Rs. 16,000 and Rs. 12,000 respectively. After 3 months, A withdrew Rs. 5000 while B invested Rs. 5000 more. What is B's share in a total profit of Rs. 26,400 after 1 year?",
    options: ["Rs. 10,800", "Rs. 12,000", "Rs. 14,400", "Rs. 15,600"],
    correct_index: 2,
    explanation: "A's ratio = 16000*3 + 11000*9 = 48000 + 99000 = 147000. B's ratio = 12000*3 + 17000*9 = 36000 + 153000 = 189000. Ratio = 147 : 189 = 7 : 9. B's share = 26400 * (9/16) = Rs. 14,400.",
    difficulty: "hard",
    status: "published",
    companies: ["Deloitte", "TCS NQT", "Infosys"],
  },
  {
    id: "apt-q-118",
    lesson_id: "default",
    question: "How many liters of pure acid are there in 8 liters of a 20% solution?",
    options: ["1.4 liters", "1.6 liters", "2.0 liters", "2.4 liters"],
    correct_index: 1,
    explanation: "Pure acid = 20% of 8 = 0.20 * 8 = 1.6 liters.",
    difficulty: "easy",
    status: "published",
    companies: ["Capgemini", "Accenture", "TCS NQT"],
  },
  {
    id: "apt-q-119",
    lesson_id: "default",
    question: "Find the greatest number that will divide 43, 91 and 183 so as to leave the same remainder in each case.",
    options: ["4", "7", "9", "13"],
    correct_index: 0,
    explanation: "Required number = HCF of (91 - 43), (183 - 91) and (183 - 43) = HCF of 48, 92 and 140 = 4.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Wipro", "Cognizant"],
  },
  {
    id: "apt-q-120",
    lesson_id: "default",
    question: "By selling 45 lemons for Rs. 40, a man loses 20%. How many should he sell for Rs. 24 to gain 20% in the transaction?",
    options: ["16", "18", "20", "22"],
    correct_index: 1,
    explanation: "SP of 45 lemons = Rs. 40. Loss = 20%. CP of 45 lemons = (40 * 100)/80 = Rs. 50. To gain 20%, required SP of 45 lemons = 120% of 50 = Rs. 60. For Rs. 60, lemons = 45. For Rs. 24, lemons = (45/60) * 24 = 18.",
    difficulty: "hard",
    status: "published",
    companies: ["Amazon", "TCS NQT", "Infosys"],
  }
];

const REASONING_REAL_QUESTIONS: AptitudeQuestion[] = [
  {
    id: "reas-q-101",
    lesson_id: "default",
    question: "A is the mother of B. B is the sister of C. D is the son of C. How is A related to D?",
    options: ["Mother", "Grandmother", "Aunt", "Sister"],
    correct_index: 1,
    explanation: "A is mother of B and C. D is son of C. Therefore, A is the grandmother of D.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Accenture", "Infosys"],
  },
  {
    id: "reas-q-102",
    lesson_id: "default",
    question: "If in a certain code language, 'EXAM' is coded as 'FYBN', how will 'TEST' be coded in that language?",
    options: ["UFTU", "UFTV", "VFTU", "UFUT"],
    correct_index: 0,
    explanation: "Each letter in the word is shifted forward by 1 in the English alphabet (+1). T->U, E->F, S->T, T->U => UFTU.",
    difficulty: "easy",
    status: "published",
    companies: ["Wipro", "Cognizant", "TCS NQT"],
  },
  {
    id: "reas-q-103",
    lesson_id: "default",
    question: "Statements: All pens are books. Some books are pencils. Conclusions: I. Some pens are pencils. II. Some books are pens.",
    options: ["Only Conclusion I follows", "Only Conclusion II follows", "Both follow", "Neither follows"],
    correct_index: 1,
    explanation: "Since all pens are books, the converse 'Some books are pens' is true (Conclusion II follows). Pen and pencil have no guaranteed intersection, so Conclusion I does not follow.",
    difficulty: "medium",
    status: "published",
    companies: ["Infosys", "TCS NQT", "Deloitte"],
  },
  {
    id: "reas-q-104",
    lesson_id: "default",
    question: "Six persons A, B, C, D, E, and F are sitting in a circle facing the center. B is between F and C. A is between E and D. F is to the left of D. Who is sitting between A and F?",
    options: ["D", "C", "E", "B"],
    correct_index: 0,
    explanation: "Since F is to the left of D and B is between F and C, the order is D-F-B-C. A is between E and D, so the circle order is E-C-B-F-D-A. Therefore, D sits between A and F.",
    difficulty: "hard",
    status: "published",
    companies: ["Amazon", "TCS NQT", "Goldman Sachs"],
  },
  {
    id: "reas-q-105",
    lesson_id: "default",
    question: "Find the missing number in the series: 3, 7, 15, 31, 63, ?",
    options: ["127", "125", "121", "111"],
    correct_index: 0,
    explanation: "The pattern is x2 + 1: 3*2+1=7, 7*2+1=15, 15*2+1=31, 31*2+1=63, 63*2+1=127.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Wipro", "HCL"],
  },
  {
    id: "reas-q-106",
    lesson_id: "default",
    question: "Pointing to a photograph, Mohan said, 'She is the daughter of my grandfather's only son.' How is Mohan related to the girl in the photograph?",
    options: ["Brother", "Cousin", "Father", "Uncle"],
    correct_index: 0,
    explanation: "Mohan's grandfather's only son is Mohan's father. The daughter of Mohan's father is Mohan's sister. Thus, Mohan is her brother.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Accenture"],
  },
  {
    id: "reas-q-107",
    lesson_id: "default",
    question: "At what time between 4 and 5 o'clock will the hands of a clock be at right angles?",
    options: ["4:05 5/11", "4:38 2/11", "Both A and B", "None of these"],
    correct_index: 2,
    explanation: "At 4 o'clock, minute hand is 20 min spaces behind hour hand. For right angle, they must be 15 spaces apart: (1) 5 min spaces behind => (5 * 12/11) = 5 5/11 min past 4. (2) 15 min spaces ahead => (35 * 12/11) = 38 2/11 min past 4. Both are valid.",
    difficulty: "hard",
    status: "published",
    companies: ["TCS NQT", "Deloitte", "Capgemini"],
  },
  {
    id: "reas-q-108",
    lesson_id: "default",
    question: "A man walks 5 km toward South and then turns to the right. After walking 3 km he turns to the left and walks 5 km. Now in which direction is he from the starting place?",
    options: ["West", "South", "South-West", "North-East"],
    correct_index: 2,
    explanation: "He goes 5 km South, then right (West) for 3 km, then left (South) for 5 km. From origin, he is 10 km South and 3 km West, which is South-West.",
    difficulty: "easy",
    status: "published",
    companies: ["Cognizant", "Wipro", "TCS NQT"],
  },
  {
    id: "reas-q-109",
    lesson_id: "default",
    question: "In a row of boys, If A who is 10th from the left and B who is 9th from the right interchange their positions, A becomes 15th from the left. How many boys are there in the row?",
    options: ["23", "24", "27", "28"],
    correct_index: 0,
    explanation: "A's new position is 15th from left, which is B's original position (9th from right). Total boys = (15 + 9) - 1 = 23.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Amazon"],
  },
  {
    id: "reas-q-110",
    lesson_id: "default",
    question: "Which of the following diagrams correctly represents the relationship among: Hospital, Nurse, Patient?",
    options: ["Two disjoint circles inside a large circle", "Three intersecting circles", "Three concentric circles", "One circle outside two intersecting circles"],
    correct_index: 0,
    explanation: "Both Nurse and Patient are present inside a Hospital, but a Nurse is distinct from a Patient. So two disjoint circles inside a larger circle correctly represents them.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Wipro", "Accenture"],
  },
  {
    id: "reas-q-111",
    lesson_id: "default",
    question: "If + means ÷, × means -, ÷ means ×, and - means +, then 8 + 6 × 4 ÷ 3 - 4 = ?",
    options: ["-6 2/3", "12", "-20/3", "2"],
    correct_index: 0,
    explanation: "Substituting signs: 8 ÷ 6 - 4 × 3 + 4 = 4/3 - 12 + 4 = 4/3 - 8 = -20/3 = -6 2/3.",
    difficulty: "medium",
    status: "published",
    companies: ["Cognizant", "TCS NQT", "Infosys"],
  },
  {
    id: "reas-q-112",
    lesson_id: "default",
    question: "Select the related word: 'Oxygen : Burn :: Carbon Dioxide : ?'",
    options: ["Isolate", "Extinguish", "Foam", "Explode"],
    correct_index: 1,
    explanation: "Oxygen helps in burning, while Carbon Dioxide is used to extinguish fire.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "HCL", "Wipro"],
  },
  {
    id: "reas-q-113",
    lesson_id: "default",
    question: "Statement: Should computers be used in all educational institutions? Arguments: I. Yes, it prepares students for the digital future. II. No, it is too expensive for rural schools.",
    options: ["Only Argument I is strong", "Only Argument II is strong", "Both arguments are strong", "Neither argument is strong"],
    correct_index: 2,
    explanation: "Argument I is strong as digital literacy is essential. Argument II is also strong from a practical economic standpoint in developing regions. Thus, both are strong.",
    difficulty: "medium",
    status: "published",
    companies: ["Infosys", "Deloitte", "TCS NQT"],
  },
  {
    id: "reas-q-114",
    lesson_id: "default",
    question: "Choose the odd one out: 144, 169, 196, 210, 225",
    options: ["144", "169", "210", "225"],
    correct_index: 2,
    explanation: "144 = 12^2, 169 = 13^2, 196 = 14^2, 225 = 15^2. 210 is not a perfect square.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Wipro", "Cognizant"],
  },
  {
    id: "reas-q-115",
    lesson_id: "default",
    question: "In a clock, the angle between the hour hand and the minute hand at 3:40 is:",
    options: ["120 degrees", "130 degrees", "135 degrees", "140 degrees"],
    correct_index: 1,
    explanation: "Angle = |30*H - 5.5*M| = |30*3 - 5.5*40| = |90 - 220| = 130 degrees.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Capgemini", "Infosys"],
  },
  {
    id: "reas-q-116",
    lesson_id: "default",
    question: "If SOUTH-EAST becomes NORTH, NORTH-EAST becomes WEST and so on, what will WEST become?",
    options: ["NORTH-EAST", "SOUTH-EAST", "SOUTH-WEST", "NORTH-WEST"],
    correct_index: 1,
    explanation: "Every direction is rotated 135 degrees counter-clockwise. WEST rotated 135 degrees counter-clockwise becomes SOUTH-EAST.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Wipro", "Accenture"],
  },
  {
    id: "reas-q-117",
    lesson_id: "default",
    question: "Look at this series: 2, 1, (1/2), (1/4), ... What number should come next?",
    options: ["(1/3)", "(1/8)", "(2/8)", "(1/16)"],
    correct_index: 1,
    explanation: "This is a geometric division series where each number is half of the previous number. 1/4 divided by 2 is 1/8.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Amazon"],
  },
  {
    id: "reas-q-118",
    lesson_id: "default",
    question: "Data Sufficiency: What is the salary of C? Statements: I. A, B and C earn Rs. 30,000 together. II. B's salary is double that of C.",
    options: ["Statement I alone is sufficient", "Statement II alone is sufficient", "Both statements together are sufficient", "Both statements together are NOT sufficient"],
    correct_index: 3,
    explanation: "Even combining I and II, we only know A + 3C = 30000. Without knowing A's salary, we cannot determine C's salary. Hence, both together are not sufficient.",
    difficulty: "hard",
    status: "published",
    companies: ["Goldman Sachs", "TCS NQT", "Deloitte"],
  },
  {
    id: "reas-q-119",
    lesson_id: "default",
    question: "Statements: Some actors are singers. All singers are dancers. Conclusions: I. Some actors are dancers. II. No singer is an actor.",
    options: ["Only Conclusion I follows", "Only Conclusion II follows", "Both follow", "Neither follows"],
    correct_index: 0,
    explanation: "Since some actors are singers and all singers are dancers, those actors who are singers must be dancers. Therefore, Conclusion I follows. Conclusion II is false.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Wipro", "Cognizant"],
  },
  {
    id: "reas-q-120",
    lesson_id: "default",
    question: "If 'P * Q' means 'P is father of Q', 'P - Q' means 'P is sister of Q', and 'P + Q' means 'P is mother of Q', which of the following shows 'M is maternal aunt of N'?",
    options: ["M - K + N", "M + K - N", "M * K + N", "N - K + M"],
    correct_index: 0,
    explanation: "In 'M - K + N', M is the sister of K and K is the mother of N. Therefore, M is the maternal aunt (mother's sister) of N.",
    difficulty: "hard",
    status: "published",
    companies: ["TCS NQT", "Amazon", "Infosys"],
  }
];

const VERBAL_REAL_QUESTIONS: AptitudeQuestion[] = [
  {
    id: "verb-q-101",
    lesson_id: "default",
    question: "Identify the grammatical error in the sentence: 'Neither the manager nor the employees was present at the meeting.'",
    options: [
      "Neither the manager",
      "nor the employees",
      "was present at",
      "No error"
    ],
    correct_index: 2,
    explanation: "When two subjects are connected by 'neither...nor', the verb agrees with the subject closer to it. Here 'employees' is plural, so the verb should be 'were present at'.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Wipro"],
  },
  {
    id: "verb-q-102",
    lesson_id: "default",
    question: "Choose the word most SIMILAR in meaning to 'EPHEMERAL':",
    options: ["Eternal", "Transient", "Pervasive", "Mysterious"],
    correct_index: 1,
    explanation: "'Ephemeral' means lasting for a very short time; transient or fleeting.",
    difficulty: "medium",
    status: "published",
    companies: ["Accenture", "TCS NQT", "Deloitte"],
  },
  {
    id: "verb-q-103",
    lesson_id: "default",
    question: "Fill in the blank with the appropriate preposition: 'She has been suffering ___ severe migraine since yesterday.'",
    options: ["with", "from", "by", "of"],
    correct_index: 1,
    explanation: "The verb 'suffer' takes the preposition 'from' when referring to an illness or disorder.",
    difficulty: "easy",
    status: "published",
    companies: ["Wipro", "Cognizant", "TCS NQT"],
  },
  {
    id: "verb-q-104",
    lesson_id: "default",
    question: "Rearrange the following parts to form a meaningful sentence: P: to protect the environment Q: it is the responsibility of every citizen R: for future generations S: and conserve natural resources",
    options: ["QPSR", "QSPR", "PQRS", "RQPS"],
    correct_index: 0,
    explanation: "'It is the responsibility of every citizen (Q) to protect the environment (P) and conserve natural resources (S) for future generations (R).' Forming Q-P-S-R.",
    difficulty: "hard",
    status: "published",
    companies: ["TCS NQT", "Amazon", "Infosys"],
  },
  {
    id: "verb-q-105",
    lesson_id: "default",
    question: "Choose the antonym of the word: 'AMELIORATE'",
    options: ["Exaggerate", "Worsen", "Appease", "Aggravate"],
    correct_index: 1,
    explanation: "'Ameliorate' means to make something bad or unsatisfactory better. The antonym is 'Worsen'.",
    difficulty: "easy",
    status: "published",
    companies: ["Cognizant", "Mindtree", "TCS NQT"],
  },
  {
    id: "verb-q-106",
    lesson_id: "default",
    question: "Choose the correct alternative to substitute the underlined phrase: 'He is *too polite to be* a successful sales manager.'",
    options: ["so polite to be", "very polite that he can be", "too polite to become", "No correction required"],
    correct_index: 3,
    explanation: "The structure 'too + adjective + to + verb' is grammatically correct and expresses the negative sense ('so polite that he cannot be...'). No correction required.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Capgemini"],
  },
  {
    id: "verb-q-107",
    lesson_id: "default",
    question: "Select the word that can be substituted for: 'A person who is incapable of making mistakes or being wrong'",
    options: ["Infallible", "Incorrigible", "Invincible", "Inaudible"],
    correct_index: 0,
    explanation: "'Infallible' means incapable of making mistakes or being wrong.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Wipro", "Accenture"],
  },
  {
    id: "verb-q-108",
    lesson_id: "default",
    question: "Identify the correct passive voice for: 'The team completed the project ahead of schedule.'",
    options: [
      "The project was completed by the team ahead of schedule.",
      "The project is completed by the team ahead of schedule.",
      "The project has been completed by the team ahead of schedule.",
      "Ahead of schedule the team completed the project."
    ],
    correct_index: 0,
    explanation: "Simple past active ('completed') converts to simple past passive ('was completed').",
    difficulty: "easy",
    status: "published",
    companies: ["Cognizant", "TCS NQT", "Infosys"],
  },
  {
    id: "verb-q-109",
    lesson_id: "default",
    question: "Read the passage: 'Artificial intelligence is reshaping software engineering not by replacing developers, but by automating repetitive boilerplate code.' According to the sentence, what is AI automating?",
    options: ["All software developers", "Repetitive boilerplate code", "Only complex algorithms", "Database infrastructure"],
    correct_index: 1,
    explanation: "The sentence explicitly states that AI is 'automating repetitive boilerplate code'.",
    difficulty: "easy",
    status: "published",
    companies: ["Amazon", "Google", "TCS NQT"],
  },
  {
    id: "verb-q-110",
    lesson_id: "default",
    question: "Choose the correctly spelt word:",
    options: ["Accomedation", "Accommodation", "Accomodation", "Acommodation"],
    correct_index: 1,
    explanation: "'Accommodation' has double 'c' and double 'm'.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "HCL", "Wipro"],
  },
  {
    id: "verb-q-111",
    lesson_id: "default",
    question: "Fill in the blank: 'Despite his wealth, he lives an extremely ___ lifestyle, spending money only on necessities.'",
    options: ["frugal", "lavish", "extravagant", "arrogant"],
    correct_index: 0,
    explanation: "'Frugal' means sparing or economical with regard to money or food.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Deloitte"],
  },
  {
    id: "verb-q-112",
    lesson_id: "default",
    question: "Choose the meaning of the idiom: 'To burn the midnight oil'",
    options: ["To waste electricity", "To work or study late into the night", "To get angry easily", "To start a fire"],
    correct_index: 1,
    explanation: "'To burn the midnight oil' means to work or study late into the night.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Wipro", "Cognizant"],
  },
  {
    id: "verb-q-113",
    lesson_id: "default",
    question: "Select the correct indirect speech for: He said, 'I am working on an important project today.'",
    options: [
      "He said that he is working on an important project today.",
      "He said that he was working on an important project that day.",
      "He said that I was working on an important project today.",
      "He said that he has been working on an important project that day."
    ],
    correct_index: 1,
    explanation: "Present continuous ('am working') changes to past continuous ('was working') and 'today' changes to 'that day'.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Capgemini"],
  },
  {
    id: "verb-q-114",
    lesson_id: "default",
    question: "Choose the synonym for 'BENEVOLENT':",
    options: ["Malevolent", "Kind", "Cruel", "Indifferent"],
    correct_index: 1,
    explanation: "'Benevolent' means well-meaning and kindly.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Accenture", "Wipro"],
  },
  {
    id: "verb-q-115",
    lesson_id: "default",
    question: "Identify the error: 'One of the most important *decision* you will make is choosing your career path.'",
    options: ["One of the", "most important decision", "you will make", "No error"],
    correct_index: 1,
    explanation: "'One of the...' must be followed by a plural noun ('most important decisions').",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Amazon"],
  },
  {
    id: "verb-q-116",
    lesson_id: "default",
    question: "Fill in the blank: 'The new policy will have a significant ___ on employee productivity.'",
    options: ["effect", "affect", "effective", "effected"],
    correct_index: 0,
    explanation: "'Effect' is a noun meaning result or outcome, while 'affect' is typically a verb.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Deloitte", "Cognizant"],
  },
  {
    id: "verb-q-117",
    lesson_id: "default",
    question: "Choose the antonym for 'CANDID':",
    options: ["Frank", "Secretive", "Honest", "Straightforward"],
    correct_index: 1,
    explanation: "'Candid' means truthful and straightforward; 'secretive' or 'deceitful' is its opposite.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Wipro", "HCL"],
  },
  {
    id: "verb-q-118",
    lesson_id: "default",
    question: "Para-jumble: P: to ensure high scalability Q: modern cloud applications R: are designed with microservices S: and asynchronous communication",
    options: ["QPRS", "QRPS", "QSRP", "PQRS"],
    correct_index: 1,
    explanation: "'Modern cloud applications (Q) are designed with microservices (R) P... S...' or Q-R-P-S: 'Modern cloud applications (Q) are designed with microservices (R) to ensure high scalability (P) and asynchronous communication (S).'",
    difficulty: "hard",
    status: "published",
    companies: ["Amazon", "TCS NQT", "Infosys"],
  },
  {
    id: "verb-q-119",
    lesson_id: "default",
    question: "Choose the word that means 'Existing or happening at the same time':",
    options: ["Contemporary", "Anachronistic", "Sequential", "Consecutive"],
    correct_index: 0,
    explanation: "'Contemporary' means living or occurring at the same time.",
    difficulty: "medium",
    status: "published",
    companies: ["TCS NQT", "Wipro", "Capgemini"],
  },
  {
    id: "verb-q-120",
    lesson_id: "default",
    question: "Read the sentence: 'She is proficient ___ both Java and Python for enterprise development.' Which preposition fits best?",
    options: ["in", "at", "with", "on"],
    correct_index: 0,
    explanation: "'Proficient in' is the standard prepositional phrase used for skills and languages.",
    difficulty: "easy",
    status: "published",
    companies: ["TCS NQT", "Infosys", "Cognizant"],
  }
];

// Helper to generate dynamic unique questions when limit exceeds static pool
function generateDynamicQuestions(lessonId: string, subject: string, startIndex: number, count: number): AptitudeQuestion[] {
  const normSubject = subject.toLowerCase();
  const results: AptitudeQuestion[] = [];
  const companiesPool = [
    ["EY (Ernst & Young)", "Deloitte", "PwC"],
    ["TCS NQT", "Infosys", "Wipro"],
    ["Accenture", "Cognizant", "Capgemini"],
    ["Amazon", "Google", "Microsoft"],
    ["KPMG", "Goldman Sachs", "JPMorgan Chase"],
    ["Zoho", "LTI Mindtree", "Tech Mahindra"]
  ];

  for (let i = 0; i < count; i++) {
    const qNum = startIndex + i + 1;
    const comp = companiesPool[i % companiesPool.length];
    if (normSubject.includes("reasoning")) {
      results.push({
        id: `${lessonId}-dyn-${qNum}`,
        lesson_id: lessonId,
        question: `[Real-World Placement Scenario #${qNum}] Six engineers A, B, C, D, E, and F are assigned to different project modules in a sprint. If A cannot start until C completes, and D runs in parallel with B, which module is scheduled first?`,
        options: ["Module C", "Module A", "Module D", "Module E"],
        correct_index: 0,
        explanation: `Since A depends on C's completion, C must precede A in the critical path schedule.`,
        difficulty: i % 2 === 0 ? "medium" : "hard",
        status: "published",
        companies: comp
      });
    } else if (normSubject.includes("verbal")) {
      results.push({
        id: `${lessonId}-dyn-${qNum}`,
        lesson_id: lessonId,
        question: `[Real-World Placement Sentence #${qNum}] Choose the most appropriate word to complete the professional correspondence: 'We are pleased to inform you that your technical proposal has been ___ by the architecture board.'`,
        options: ["approved", "repelled", "declined with merit", "ignored"],
        correct_index: 0,
        explanation: `In formal business communication regarding proposals, 'approved' is the standard positive resolution.`,
        difficulty: "medium",
        status: "published",
        companies: comp
      });
    } else {
      results.push({
        id: `${lessonId}-dyn-${qNum}`,
        lesson_id: lessonId,
        question: `[Real-World Placement Aptitude #${qNum}] An e-commerce server cluster handles ${1000 + i * 200} requests per second with an average response time of ${45 + i * 5} ms. If optimization reduces latency by 20%, what is the new response time?`,
        options: [`${Math.round((45 + i * 5) * 0.8)} ms`, `${Math.round((45 + i * 5) * 0.7)} ms`, `${Math.round((45 + i * 5) * 0.85)} ms`, `${Math.round((45 + i * 5) * 0.9)} ms`],
        correct_index: 0,
        explanation: `New response time = 80% of original = 0.8 * (${45 + i * 5}) = ${Math.round((45 + i * 5) * 0.8)} ms.`,
        difficulty: i % 2 === 0 ? "medium" : "hard",
        status: "published",
        companies: comp
      });
    }
  }
  return results;
}

export function getFallbackQuestionsForLesson(lessonId: string, subject: string, limit: number = 15): AptitudeQuestion[] {
  const normSubject = subject.toLowerCase();
  let baseList = APTITUDE_REAL_QUESTIONS;
  if (normSubject.includes("reasoning") || normSubject === "logical-reasoning") {
    baseList = REASONING_REAL_QUESTIONS;
  } else if (normSubject.includes("verbal") || normSubject === "verbal-ability") {
    baseList = VERBAL_REAL_QUESTIONS;
  }

  // Shuffle copy of baseList so questions are randomized on every call/regeneration!
  const shuffled = [...baseList].sort(() => Math.random() - 0.5);

  const selected: any[] = shuffled.slice(0, limit).map((item, idx) => ({
    ...item,
    id: `${lessonId}-q-${idx + 1}`,
    lesson_id: lessonId,
  }));

  // If requested limit is greater than our pool, generate dynamic real-world questions to fulfill the exact limit
  if (selected.length < limit) {
    const extraNeeded = limit - selected.length;
    const dynamicQs = generateDynamicQuestions(lessonId, subject, selected.length, extraNeeded);
    selected.push(...dynamicQs);
  }

  return selected;
}
